---
name: "release"

on:
  push:
jobs:
  pre-release:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"

      - name: Apply Patches
        run: ./gradlew applyAllPatches --stacktrace

      - name: Build
        run: ./gradlew createMojmapPaperclipJar

      - name: Create Release (development)
        if: github.ref != 'refs/heads/master'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-dev"
          prerelease: false
          title: "Development Build"
          files: |
            sparklyslimepaper-server/build/libs/*-mojmap.jar

      - name: Create Release (master)
        if: github.ref == 'refs/heads/master'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-prod"
          prerelease: false
          title: "Production Build"
          files: |
            sparklyslimepaper-server/build/libs/*-mojmap.jar
